#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"
#theme = "hugo-dusk"


baseurl = "/"
title = "LuaDist2 Packages"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "beautifulhugo"

